- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Delete local directory
      file: path=/home/stanco/wsn/logs/ state=absent


- name: Fetch log folder from remote machines to local.
  hosts: iris1
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/root.iris1.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['flash.log','motelist.log','root_server.log','service.log','tunslip.log']

- name: Fetch log folder from remote machines to local.
  hosts: iris3
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/edge.iris3.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['challenge_response.log','edge_bridge.log','flash.log','monitoring.log','motelist.log','packet.log','routing.log']

- name: Fetch log folder from remote machines to local.
  hosts: iris10
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/edge.iris10.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['challenge_response.log','edge_bridge.log','flash.log','monitoring.log','motelist.log','packet.log','routing.log']

- name: Fetch log folder from remote machines to local.
  hosts: iris2
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/wsn.iris2.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['flash.log', 'motelist.log','packet.log','pyterm.log']

- name: Fetch log folder from remote machines to local.
  hosts: iris4
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/wsn.iris4.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['flash.log', 'motelist.log','packet.log','pyterm.log']

- name: Fetch log folder from remote machines to local.
  hosts: iris5
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/wsn.iris5.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['flash.log', 'motelist.log','packet.log','pyterm.log']

- name: Fetch log folder from remote machines to local.
  hosts: iris6
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/wsn.iris6.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['flash.log', 'motelist.log','packet.log','pyterm.log']

- name: Fetch log folder from remote machines to local.
  hosts: iris7
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/wsn.iris7.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['flash.log', 'motelist.log','packet.log','pyterm.log']

- name: Fetch log folder from remote machines to local.
  hosts: iris9
  tasks:
  - name: Fetching folder
    fetch:
      src: /home/gstanco/deploy/iot-trust-task-alloc/logs/wsn.iris9.{{item}}
      dest: /home/stanco/wsn/logs/
      flat: yes
    with_items:
      ['flash.log', 'motelist.log','packet.log','pyterm.log']
