---
- name: Motelist
  hosts: all
  gather_facts: false

  vars:
    output: "table"

  tasks:
  - name: Mostlist
    ansible.builtin.command: "python3 ~/deploy/iot-trust-task-alloc/tools/deploy/motelist_backend/nrf.py --output {{ output }}"
    register: motelist_output

  - debug:
      var: motelist_output.stdout
