---
- name: Setup root
  hosts: iris1
  gather_facts: no

  tasks:
  - name: Clone contiki
    ansible.builtin.git:
      repo: https://github.com/MBradbury/contiki-ng.git
      dest: ~/deploy/contiki-ng
      version: petras
      recursive: yes
      force: yes

  - name: Clean tunslip
    ansible.builtin.command:
      cmd: make clean
      chdir: ~/deploy/contiki-ng/tools/serial-io

  - name: Build tunslip
    ansible.builtin.command:
      cmd: make
      chdir: ~/deploy/contiki-ng/tools/serial-io

  - name: Clean border router native
    ansible.builtin.command:
      cmd: make clean
      chdir: ~/deploy/contiki-ng/examples/rpl-border-router

  - name: Build border router native
    ansible.builtin.command:
      cmd: make TARGET=native
      chdir: ~/deploy/contiki-ng/examples/rpl-border-router
